### ISSUE TITLE
Publish curiostack-pom to jcenter etc

### ISSUE THREAD

**Issue by gavinreaney** [curioswitch/curiostack#312]
I'm not sure if this is a new thing or not but we received a complaint about java builds failing due to dependency issues when clients tried to use the latest version of our API (see link below).

To recap: we are using curiostack plugin to build Java API stubs and publishing them on jcenter and maven central.

However, our POM file now includes 'curiostack-pom' as a dependencyManagement entry:
https://jcenter.bintray.com/com/stellarstation/api/stellarstation-api/0.3.0/:stellarstation-api-0.3.0.pom

The issue here is that clients of our API will need to add something like the following in their own builds since that artifact isn't in the usual repos.

```
maven {
    url 'http://dl.bintray.com/curioswitch/curiostack'
}
```

Can the artifact be made available in the usual repos?

**Comment by chokoswitch** [comment]
Thanks for reporting. This is because of switching from spring dependencies plugin to Gradle's native functionality for dependency management. But it seems the latter is implemented a little differently. I have requested for addition to jcenter and will publish to maven central once that's in, in a few hours. 

Also filed #313 since for those sort of projects, it might be better to not use the bom at all.

**Comment by chokoswitch** [comment]
POM's on maven central and jcenter now.
