### ISSUE TITLE
[question] How to pass environment to Go plugin?

### ISSUE THREAD

**Issue by fkorotkov** [curioswitch/curiostack#480]
Hello there,

I've been researching alternatives to `gogradle` plugin since it was flaking dependency resolution pretty frequently and I came across you go plugin for Gradle which uses the native dependency resolution instead of a custom one. I've started trying to migrate but noticed that it seems not to be possible to pass custom environment  variables like `CGO_ENABLED` to `goBuild` task for example.

If my assumption is right I'd be more then happy to work on adding such functionality if you'll be OK with that.

**Comment by danada** [comment]
How about something like this in your `build.gradle`?

```go
afterEvaluate {
    tasks.withType(org.curioswitch.gradle.golang.tasks.GoTask).configureEach { task ->
        if (task.name.startsWith('goBuild')) {
            task.execCustomizer {
                environment 'CGO_ENABLED', '0'
            }
        }
    }
}
```

**Comment by chokoswitch** [comment]
Hi @fkorotkov - thanks for your interest in the plugin. As @danada points out, rather than copying all the knobs for exec customization, there is just an `execCustomizer` method that accepts a closure which is passed [ExecSpec](https://docs.gradle.org/current/javadoc/org/gradle/process/ExecSpec.html). I have added an example / regression test here - https://github.com/curioswitch/curiostack/tree/master/tools/gradle-plugins/gradle-golang-plugin/src/test/resources/test-projects/cgo-disabled

The plugins here have evolved through usage in large projects with lots of opinions. Some opinions in the go plugin include

- Downloading [miniconda](https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html) to allow cgo binaries to be compiled even when the host does not have a native compile toolchain
- Set `GOFLAGS=-mod=readonly` to ensure CI has consistent builds
- Require `gofmt` for the build, despite go team's recommendation against that

These are considered best practices by the overall curiostack and I'd always keep them as defaults - but I'm more than happy to add more knobs to disable some of this opinionated behavior if it helps additional use cases. Let me know if there's anything that would help you, and always happy to review pull requests :)

**Comment by fkorotkov** [comment]
Awesome! Will try it out! Thanks for the fast response!
