### ISSUE TITLE
Task :toolsFetchCache... Fails frequently

### ISSUE THREAD

**Issue by davidk81** [curioswitch/curiostack#533]
these tasks have been failing frequently in our CI and requires manual retry which eventually leads to success.
- toolsFetchCacheGcloud
- toolsFetchCacheMinicondaBuild

I'm trying to track down the source of this issue (perhaps our API limits are reached?) but I'm not sure where to begin. I'd also be interested in knowing how I can make this task retry automatically if there are no better solutions. 

the error message from the failed tasks:
```
Traceback...
...
Step #3 - "build-all": socket.error: [Errno 104] Connection reset by peer
Step #3 - "build-all": Error 68 : Unfinished stream 
Step #3 - "build-all": tar: Unexpected EOF in archive
Step #3 - "build-all": tar: Unexpected EOF in archive
Step #3 - "build-all": tar: Error is not recoverable: exiting now
```

Thanks!

**Comment by chokoswitch** [comment]
Thanks for the report. The fetch is coded her

https://github.com/curioswitch/curiostack/blob/master/tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/tasks/FetchToolCacheTask.java

gsutil automatically retries on transient failures

https://cloud.google.com/storage/docs/gsutil/commands/cp#retry-handling_1

But while I can't find this documented, I'm guessing it doesn't retry when piping to a stream like we are doing, given if it did there's no way the downstream would be able to handle that properly. Let me try tweaking this so it downloads to a tmp file instead of straight into a stream.

**Comment by davidk81** [comment]
thanks for the quick response!

i did suspect its was a failure with google storage transfer, but our console doesn't seem to indicate any storage API limits being reached. Sometimes we would get 3 or 4 consecutive failed builds before it succeeds which makes me suspect something else is at play here other than random network failures.

would greatly appreciate you spending time on this, i'm not sure how to fork and test custom changes to **curiostack** against our project yet.

**Comment by chokoswitch** [comment]
Thanks - unfortunately testing things with cloud build and a local snapshot tends to be pretty difficult, and maybe not worth the time. I'll look into this tomorrow, in the meantime I think you can disable the task in your build, which may sacrifice some time by redownloading stuff from external sources, but would avoid the gsutil flakiness I think. Cloud Storage is designed to require retries, so I'm not surprised if this has nothing to do with API limits.

I haven't tested the syntax exactly, but something like this in the top level build should disable things (groovy since I recall you still using it)
```groovy
afterEvaluate {
  tasks.each {task ->
    if (task.name.startsWith("toolsFetchCache")) task.enabled = false
  }
}
```

**Comment by chokoswitch** [comment]
@davidk81 I just noticed that `FetchToolCacheTask` already has `exec.setIgnoreExitValue(true)` - failures in gsutil should not be failing the task. Are you sure those tasks are actually failing? If you can post a bit more log output that would be nice. I think step 3 is usually fetching build cache in the cloudbuild, not the Gradle tasks. Though those too should ignore failure if suffixed with `|| echo Could not fetch compressed build cache...`

That being said, I think it is better to migrate both of these off of streams but want to confirm what exactly the failure is you're seeing.

**Comment by chokoswitch** [comment]
Also just noticed curiostack is currently using a stream for the master build but a temp file for the PR build. Will switch master to temp file too as a reference point.

**Comment by davidk81** [comment]
you're right, but it seems to cause the parent(?) task to fail

```
Step #3 - "build-all": > Task :toolsFetchCacheMinicondaBuild
Step #3 - "build-all": Traceback (most recent call last):
Step #3 - "build-all":   File "/usr/lib/google-cloud-sdk/platform/gsutil/gsutil", line 21, in <module>
Step #3 - "build-all":     gsutil.RunMain()
...
Step #3 - "build-all":   File "/usr/lib/python2.7/ssl.py", line 641, in read
Step #3 - "build-all":     v = self._sslobj.read(len)
Step #3 - "build-all": socket.error: [Errno 104] Connection reset by peer
Step #3 - "build-all": 
Step #3 - "build-all": > Task :fetchCodeCovCache
Step #3 - "build-all": 
Step #3 - "build-all": > Task :toolsFetchCacheMinicondaBuild
Step #3 - "build-all": Error 68 : Unfinished stream 
Step #3 - "build-all": tar: Unexpected EOF in archive
Step #3 - "build-all": tar: Unexpected EOF in archive
Step #3 - "build-all": tar: Error is not recoverable: exiting now
Step #3 - "build-all": 
Step #3 - "build-all": > Task :toolsDownloadMinicondaBuild SKIPPED
Step #3 - "build-all": > Task :updateShellConfig
Step #3 - "build-all": 
Step #3 - "build-all": > Task :condaInstallPackagesMinicondaBuild FAILED
Step #3 - "build-all": Could not find platform independent libraries <prefix>
Step #3 - "build-all": Could not find platform dependent libraries <exec_prefix>
Step #3 - "build-all": Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Step #3 - "build-all": Fatal Python error: initfsencoding: Unable to get the locale encoding
Step #3 - "build-all": ModuleNotFoundError: No module named 'encodings'
Step #3 - "build-all": 
Step #3 - "build-all": Current thread 0x00007fbf3786a740 (most recent call first):
Step #3 - "build-all": 
Step #3 - "build-all": FAILURE: Build failed with an exception.
Step #3 - "build-all": 
Step #3 - "build-all": * What went wrong:
Step #3 - "build-all": Execution failed for task ':condaInstallPackagesMinicondaBuild'.
Step #3 - "build-all": > Process 'command '/root/.gradle/curiostack/miniconda-build/Miniconda3-4.7.12.1/bin/conda'' finished with non-zero exit value 134
Step #3 - "build-all": 
```

**Comment by chokoswitch** [comment]
Ah thanks for the logs, yeah I guess since the folder gets partially set up the downloads don't happen and things are broken. So if nothing else, switching to having a temp file will allow making sure the directory isn't set up even if download failed, let me actually make that more explicit in my PR.

**Comment by davidk81** [comment]
makes sense, thanks!

**Comment by chokoswitch** [comment]
I have published 0.5.0-RC1 as in https://github.com/curioswitch/curiostack/pull/536

I haven't given it a good vet yet but give it a whirl if you have a chance, I think you'll need to fix some Armeria deprecations along with it though. I'll get release notes out later. If you're already doing ok after disabling the tasks, then maybe can just wait for that :)

**Comment by chokoswitch** [comment]
0.5.1 released with the improvement to cache fetch. Now even if it fails it should not block the build completely. Let me know if you still see any issues with cache fetching.

**Comment by davidk81** [comment]
awesome, thanks! will keep you updated after it makes it into our builds.
